### ISSUE TITLE
Duplicate files in NuGet with Paket

### ISSUE THREAD

**Issue by cgravill** [natemcmaster/Yarn.MSBuild#6] opened 2017-11-29 11:08 UTC
We use the Paket tool (https://fsprojects.github.io/Paket/) to manage our NuGets.

I tried updating Yarn.MSBuild to 1.3.2 and had an error:
`IOException: Zip entry name ends in directory separator character but contains data.`

I traced back and it's same issue in 1.2.1 and 1.2.0 with the last compatible version 1.1.0.

The NuGets work perfectly fine without error using the built-in Visual Studio 2017 NuGet tool.

Inspecting the NuGet there are duplicate files in the /dist/bin directory.

If I remove these two lines:

```xml
<file src="dist/bin/yarn.cmd" target="dist/bin/" />
<file src="dist/bin/yarn" target="dist/bin/" />
```
then I'm able to install from the file locally. The overall directory is included after

```xml
<file src="dist\" target="dist/" />
```

Comparison in 7Zip of the relevant folder:

![image](https://user-images.githubusercontent.com/1099725/33371787-c020022a-d4f3-11e7-9246-5295be9bb0ec.png)

**Comment by natemcmaster** [comment] 2017-11-29 16:33
Interesting. Looks like NuGet doesnt de-dup zip entries when building the archive. Any idea if this is a known NuGet issue? If not, I’ll create a minimal repro and send them the issue.

**Comment by cgravill** [comment] 2017-11-29 19:20
I'm not aware of anything reported on this, I didn't actually know you could have duplicate entries until I isolated it. Would be great to avoid it at NuGet construction time by de-duping the entries.

**Comment by natemcmaster** [comment] 2017-11-30 01:41
I confirmed this is fixed in the nightly feed. I'll push 1.3.3 to nuget.org soon.
```
source https://www.myget.org/F/natemcmaster/api/v3/index.json

nuget Yarn.MSBuild 1.3.3-build.98
```

**Closed by natemcmaster** 2017-11-30 01:41 UTC
Labels: bug

**Comment by cgravill** [comment] 2017-11-30 11:28
Thanks, I'm using 1.3.3 from the nuget feed and it's working great
